# Generated by Django 4.1.5 on 2023-01-26 22:19

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileCnab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(9),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cpf", models.TextField(max_length=11)),
                ("card", models.TextField(max_length=12)),
                ("time", models.TimeField()),
                ("owner", models.TextField()),
                ("store", models.TextField()),
            ],
        ),
    ]
